version: '3.8'

services:
  database:
    container_name: fusiov4-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: fusiov4
      MYSQL_DATABASE: fusiov4
      MYSQL_USER: fusiov4
      MYSQL_PASSWORD: fusiov4
    ports:
      - '3308:3306'
    volumes:
      - fusiov4mysql:/var/lib/mysql

  php:
    container_name: fusiov4-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: 'develop,debug,coverage'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'

  nginx:
    container_name: fusiov4-nginx
    image: nginx:stable-alpine
    ports:
      - '82:80'
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    image: phpmyadmin
    container_name: fusiov4-phpmyadmin
    depends_on:
        - database
    ports:
        - 8083:80
    environment:
        PMA_HOST: database

volumes:
  fusiov4mysql:
    driver: local

